### ISSUE TITLE
Why is the license GPL-3.0 when there is no source code?

### ISSUE THREAD

**Issue by cgarz** [Android1500/AndroidFaker#21]
IANAL but does GPL not require the source code be made available for any publicly released binary builds?

**Comment by Android1500** [comment]
> IANAL but does GPL not require the source code be made available for any publicly released binary builds?

It was open source before but coz of some ppl i make it private they are modified my code and start to sell them without give credit or permission.

**Comment by Android1500** [comment]
> I see. That's unfortunate. If they forked the code then that code would also be covered by GPL and they would have to also provide source code. Selling binary builds I think is actually allowed so long as the source is provided. If not it should be possible to take legal action against them or depending on where it was hosted have the offending builds taken down.
> 
> 
> 
> It's just pretty weird to have a GPL project with no source available. It might also not be allowed like I mentioned at first, or it might be alright since you are the author but IANAL of course.

Agree with you but those legal thinks take a lots of time which i dont think worth thats why i removed code.

**Comment by MewX** [comment]
I think the question should be "Why is there no source code".

No source code basically means this app does lots of dodgy things.

**Comment by Android1500** [comment]
> I think the question should be "Why is there no source code".
> 
> No source code basically means this app does lots of dodgy things.

You are always free to unuse if you don't want

**Comment by Android1500** [comment]
> The license is unchanged and the source is still missing, why close the issue?
> 
> 
> 
> My previous question remains unanswered as well which makes the given reasons seem more like contrived excuses.
> 
> 
> 
> I think I'll take your advice and uninstall after all.
> 

Appericate!!!
