### ISSUE TITLE
spoofing android sdk version for a single app

### ISSUE THREAD

**Issue by iPurya** [Android1500/AndroidFaker#23]
is it possible to spoof android sdk int for a single app ?
when emulator android version is 9 i cant edit build prop but all apps crashes when increasing android sdk version.
but if there is a spoofing android sdk for a single app (changing Build.Version.SDK_INT value) i think it will work.

**Comment by Android1500** [comment]
> is it possible to spoof android sdk int for a single app ?
> 
> when emulator android version is 9 i cant edit build prop but all apps crashes when increasing android sdk version.
> 
> but if there is a spoofing android sdk for a single app (changing Build.Version.SDK_INT value) i think it will work.

Its added in v1.9.0

**Comment by iPurya** [comment]
does pro version have demo or something that i cant test before buy ?

**Comment by Android1500** [comment]
I added it in latest beta
