### ISSUE TITLE
Pro version not unlocking

### ISSUE THREAD

**Issue by SeeTurtlee** [Android1500/AndroidFaker#24]
Hi! I bought the pro version unlocked. When I go into the app and verify license it says I just have to reset the app to unlock the features. Even if I reboot it doesn't work. I've tried making an account, and reinstalling both the module and apk multiple times. Any reason for this? Thank you!

**Comment by DarkNio88** [comment]
Some problem

**Comment by SeeTurtlee** [comment]
> Same problem

Awesome. almost a year and not resolved

**Comment by Android1500** [comment]
Playstore unlocker ca.t unlock vip features of app it will only features like sim operators, media drm, gsf
