### ISSUE TITLE
caused bootloop on oneplus 8 /LSposed/ oxygen 11.0.99

### ISSUE THREAD

**Issue by mahdi89X** [Android1500/AndroidFaker#3]
caused bootloop on oneplus 8 /LSposed/ oxygen 11.0.99
android faker pro latest update

**Comment by mahdi89X** [comment]
the original 1.8.1 work perfectly but the one
with fixed cash while select usa sim operator.. that one cause bootlopp

**Comment by Android1500** [comment]
Its strange can you provide logs for better understand of issue?
