### ISSUE TITLE
Vip does not recognized (v1.9.2)

### ISSUE THREAD

**Issue by NDSTHEBEST** [Android1500/AndroidFaker#35]
I paid the vip through the Play Store, and after trying multiple times, it doesn't show me I have vip access in my account. It's super annoying.
Do you have a fix?

(Thanks,
From NDS)

Thank for purchase it from playstore but platore unlocker can unlock premium feature of app not vip one but if you purchase only vip then it will unlock both premium and vip features of app.

**Comment by Ealey77** [comment]
Same issue for me

**Comment by Android1500** [comment]
> I paid the vip through the Play Store, and after trying multiple times, it doesn't show me I have vip access in my account. It's super annoying. Do you have a fix?
> 
> (Thanks, From NDS)
> 
> Thank for purchase it from playstore but platore unlocker can unlock premium feature of app not vip one but if you purchase only vip then it will unlock both premium and vip features of app.

Playstore version not activate vip feature its only activate premium features of module like sim operator,mcc,gsf,mediadrm, remain one only unlock when you purchased vip monthy subscription.
