### ISSUE TITLE
Issue regarding Android Faker Device Spoofing option.

### ISSUE THREAD

**Issue by avisek1248** [Android1500/AndroidFaker#43]
After enabling the Device Spoofing option in Android Faker and selecting a device model, LSPosed disappears upon rebooting, and in the KernelSU module section, the Zygisk Next module displays an error message: **'Stop Inject Zygote due to Crash.'**

Android Faker Version: 1.9.2
Lsposed Version: 1.9.3
Zygisk Next Version: 1.0.4
KernelSU Version: 1.0.1

**Comment by Android1500** [comment]
It should be fixed in new version
