### ISSUE TITLE
Vip Subscribtion

### ISSUE THREAD

**Issue by farstar60** [Android1500/AndroidFaker#45]
i purchased vip three months subscription through paypal , but there are wrong letter with my email,  login  : raqyacademy@gmail.com
please activate my vip

**Comment by Android1500** [comment]
you should check before purchase even its already mention in note

**Comment by farstar60** [comment]
> you should check before purchase even its already mention in note

hello i tried to purchase a new vip v2.0 , by paypal there are an issue payment process doesn't  let me login to my paypal account to pay and always refer me to register a new paypal. please fix it
