### ISSUE TITLE
A new server doesn't work with paypal

### ISSUE THREAD

**Issue by farstar60** [Android1500/AndroidFaker#48]
hello i tried to purchase a new vip v2.0 , by paypal there are an issue payment process doesn't let me login to my paypal account to pay and always refer me to register a new paypal. please fix it

![not logn](https://github.com/user-attachments/assets/0355336b-fd7a-49e3-955d-62bc37a03d2b)

**Comment by Android1500** [comment]
> hello i tried to purchase a new vip v2.0 , by paypal there are an issue payment process doesn't let me login to my paypal account to pay and always refer me to register a new paypal. please fix it
> 
> 
> 
> ![not logn](https://github.com/user-attachments/assets/0355336b-fd7a-49e3-955d-62bc37a03d2b)
> 
> 

Strange issue i am going to check now it will fix tommorow

**Comment by Android1500** [comment]
Its fixed now can you test?

**Comment by farstar60** [comment]
> Its fixed now can you test?

hello great it work now ad i paid already but my account in AF app still give me not VIP member?

**Comment by Android1500** [comment]
> > Its fixed now can you test?
> 
> 
> 
> hello great it work now ad i paid already but my account in AF app still give me not VIP member?
> 
> this email
> 
> m.o_design@hotmail.com

Just go into account and click refresh and back to app hook page

**Comment by farstar60** [comment]
> > > Its fixed now can you test?
> > 
> > 
> > hello great it work now ad i paid already but my account in AF app still give me not VIP member?
> > this email
> > [m.o_design@hotmail.com](mailto:m.o_design@hotmail.com)
> 
> Just go into account and click refresh and back to app hook page

unfortunately , i tried more times , and cleared cache for AF app and nothing.
is it can't activate manual ?

**Comment by Android1500** [comment]
email me right nownoobdevx@gmail.com

**Comment by Android1500** [comment]
> email me right [nownoobdevx@gmail.com](mailto:nownoobdevx@gmail.com)



> > > > Its fixed now can you test?
> > > 
> > > 
> > > hello great it work now ad i paid already but my account in AF app still give me not VIP member?
> > > this email
> > > [m.o_design@hotmail.com](mailto:m.o_design@hotmail.com)
> > 
> > 
> > Just go into account and click refresh and back to app hook page
> 
> unfortunately , i tried more times , and cleared cache for AF app and nothing. is it can't activate manual ?

email me right [nownoobdevx@gmail.com](mailto:nownoobdevx@gmail.com)

**Comment by Android1500** [comment]
I hope its fixed
