### ISSUE TITLE
IMEI not masked anymore after making a phone call

### ISSUE THREAD

**Issue by rafastar2** [Android1500/AndroidFaker#59]
Hi,
Nice work, using it mainly for IMEI masking and works fine most of the time, I get proper connection to the telephone network with data, SMS's and phone calls.

But when I make or receive a regular phone call, I can speak with no problems but after the call finishes I lose connection to the phone network. Then I have to restart the phone a number of random times so it gains connection once again. I've also noticed that when I move in my car the connection is also often lost, so I suppose the problem is caused when registering into a new phone network node.

Please note that when I use data or receive SMSs the connection is rock solid and it's never lost.

**Comment by Android1500** [comment]
Don't hook system
