### ISSUE TITLE
Vip 2.0 beta

### ISSUE THREAD

**Issue by mrnobody1907** [Android1500/AndroidFaker#64]
Hello, my friend. I paid via paypal, app was android faker 2.0 beta 2, im not vip member, trying uninstall app, click Refresh - not working. Check your email please, need this app today, help me please 🙏

**Comment by Android1500** [comment]
Have you create accou t before pay

**Comment by mrnobody1907** [comment]
Yes

**Comment by Android1500** [comment]
Which plan you purchased

**Comment by mrnobody1907** [comment]
1 year of beta 2.0

**Comment by Android1500** [comment]
Give your purchase email

**Comment by mrnobody1907** [comment]
Transaction ID
4XV59629TL817045D
Im should reinstall apk now?

**Comment by mrnobody1907** [comment]
Mb account was created not in beta 2.0, idk, but im sure its was created before purchase

**Comment by mrnobody1907** [comment]
![avito-1731935822529-shot.jpg](https://github.com/user-attachments/assets/27279ae9-9fad-4d33-9482-aa8b3ba47b61)

**Comment by mrnobody1907** [comment]
iurkanov96@gmail.com
Andrei Iurkanov

Paypal email

**Comment by Android1500** [comment]
In most case it will only happen when you didnt create account before pay!!

**Comment by mrnobody1907** [comment]
![Screenshot_2024-11-18-19-37-45-66_b11fe1d558f48bc2e9f48f0b563bdf70.jpg](https://github.com/user-attachments/assets/079480e4-5da5-41f3-881a-4ad7e3786fa9)

Bro account was created before. Payid im today. Can you activate it by yourself please

**Comment by mrnobody1907** [comment]
12 November im change password

**Comment by mrnobody1907** [comment]
12 November im change password

**Comment by mrnobody1907** [comment]
You can activate it manually? Just i dont know what to do, im paid, but haven't vip. Need spoof one app today for work.

**Comment by mrnobody1907** [comment]
I can create new acc if you need for activate it manually

**Comment by mrnobody1907** [comment]
Android1500 ?

**Comment by mrnobody1907** [comment]
...

**Comment by mrnobody1907** [comment]
Bro im paid your app, give answer please. I can't understand should i wait solution or buy second phone. Its not serious. I saw comments on XDA forum how people waiting your answer 1 month    in mail. Im bought sub of your great app and cant use it. its stupid and annoying like my spam messages, but im was ready to use your app today, not tomorrow.

**Comment by Android1500** [comment]
You can create account again and purchase again i will refund this old one

**Comment by mrnobody1907** [comment]
Can you first do chargeback please? After ill make new purchase with new account

**Comment by mrnobody1907** [comment]
Will be great if you do it now, caus my friend with PayPal soon comes sleep

**Comment by mrnobody1907** [comment]
? Or im should pay twice, just im almost without money in usd

**Comment by Android1500** [comment]
Yes

**Comment by Android1500** [comment]
Give me time

**Comment by Android1500** [comment]
Give me tx id or name of paypal

**Comment by mrnobody1907** [comment]
iurkanov96@gmail.com
Andrei Iurkanov
 

Transaction ID
4XV59629TL817045D

**Comment by mrnobody1907** [comment]
Android1500

**Comment by Android1500** [comment]
Wait checking

**Comment by Android1500** [comment]
Have you purchase one year plan?

**Comment by mrnobody1907** [comment]
n1rvana27@yandex.ru account android faker. (Old account what not working)

Transaction id 4XV59629TL817045D
iurkanov96@gmail.com paypal email 
Andrei Iurkanov

Its old first payment.

2nd acc okay, working, ty.

**Comment by mrnobody1907** [comment]
Yes i purchase twice 1 year

**Comment by Android1500** [comment]
Can you raise issue in paypal?

**Comment by mrnobody1907** [comment]
![avito-1732639586969-shot.jpg](https://github.com/user-attachments/assets/66890eac-0cf5-47a0-a390-b3204c9b6d03)

Check PayPal please

**Comment by mrnobody1907** [comment]
Bro why you so slowly

**Comment by Android1500** [comment]
I already refunded to you

**Comment by mrnobody1907** [comment]
Ok. Sorry. Now im logout on second acc. And cant login![Screenshot_2024-12-04-21-11-50-84_b32194d3714b2caa39157afea762e54b.jpg](https://github.com/user-attachments/assets/054d7039-8fce-46d3-b0b5-d78cef5d32a7)
