### ISSUE TITLE
is AndroidFaker is dead?

### ISSUE THREAD

**Issue by zxczxcdev** [Android1500/AndroidFaker#69]
![image](https://github.com/user-attachments/assets/dda05c7e-8b5d-409b-8177-3c585b036830)
Im download form xposed and it error cannot be download. 
And with APK file : 
![image](https://github.com/user-attachments/assets/885f0c92-5eda-4b8b-b3a0-c80ef1c5d419)

**Comment by Zsolt8374** [comment]
That version is 2 years old. Download the beta from GitHub, also use JingMatrix's LSPosed fork.

**Comment by zxczxcdev** [comment]
Its this app really can fake device?. i try *#06# and imei not changed!
![image](https://github.com/user-attachments/assets/f2cdbda2-6945-4b15-ab36-c2a02ed83bcc)
try with 2 version apk. AF.apk and app-realase.apk ., imei not change!

**Comment by Viktor4221** [comment]
Read back in the previous issues, this was explained multiple times already. The app does work, but no app can change the IMEI towards your cell provider.

**Comment by zxczxcdev** [comment]
> Read back in the previous issues, this was explained multiple times already. The app does work, but no app can change the IMEI towards your cell provider.


So can it really change other parameters?  like mac wifi and android ssid....how to check that it is working well?

**Comment by Viktor4221** [comment]
It does not really change anything, it only changes the identifiers in the scope of specific apps (That you choose in your Xposed manager app). Those apps will see the modified identifiers. If you want to test it, just download any Device ID etc app.

**Comment by zxczxcdev** [comment]
> It does not really change anything, it only changes the identifiers in the scope of specific apps (That you choose in your Xposed manager app). Those apps will see the modified identifiers. If you want to test it, just download any Device ID etc app.

i really not see any thing change 
device ID screen shot: 
![image](https://github.com/user-attachments/assets/7d9896a5-865d-4ceb-a1d6-10340489c073)
Moduel screenshot : 
![image](https://github.com/user-attachments/assets/b82e4a92-df2b-475f-bd18-0bafbbb09f4d)
xposed setting : 
![image](https://github.com/user-attachments/assets/cf2908a7-af32-4dbd-8bce-40cb728a2c6b)

I think this app is a joke xD

**Comment by Zsolt8374** [comment]
Well, then don't use it lol No one is forcing you to, it is working for me.
