### ISSUE TITLE
VIP not activated

### ISSUE THREAD

**Issue by END-f** [Android1500/AndroidFaker#70]
I need  "v2.0.0-beta-2" features. I installed and runned it successfully but couldn't create account
So I created one with "v1.9.2" in other device and purchased VIP at https://android1500.app/

In "v2.0.0-beta-2" can't log in
In "v1.9.2" VIP not activated

My login:
fairyl**@***.com

Paypal transaction:
74X56471LE395670T

**Comment by Android1500** [comment]
first ssl certificate expired thats why you see login error which i am going to fix in next beta which going to release in 1 week then you can access vip features in beta and lets talk about v1.9.2 if you purchase from new server https://android1500.app/ then it only work for beta and upcoming release but not old v1.9.2 so just wait for next beta

**Comment by END-f** [comment]
Thanks for the clarification
like what you do
